int TEXT_SIZE = 20;
int STRIPES_NUM = 250;
int MAX_WIND = 952;
int WIND_AMPLIFICATION_FACTOR = 4;
int WIND_THRESHOLD = 40;
int FLY_THRESHOLD = 80;
int CREATE_INTERVAL = 300;
int CREATE_INTERVAL_VARIANCE = 500;

int FLY_TIME_VARIANCE = 3000;
int ROTATE_TIME_VARIANCE = 2000;
